ig=ignorepkg

# Firmware
ig = linux-firmware-broadcom
ig = linux-firmware-amd
ig = linux-firmware-nvidia

# Drivers
ig = mesa-vulkan-radeon
ig = xf86-video-amdgpu
ig = mesa-vaapi 
ig = mesa-vdpau
ig = xf86-video-nouveau
