src1 = True|wallhaven|https://wallhaven.cc/search?q=girl&categories=010&purity=100&sorting=views&order=desc&colors=424153
src2 = True|wallhaven|https://wallhaven.cc/search?q=girl&categories=001&purity=100&sorting=views&order=desc&colors=424153
src3 = True|wallhaven|https://wallhaven.cc/search?q=city+fantasy&categories=100&purity=100&sorting=views&order=desc&colors=424153

