# nmi_watchdog
# When panic is specified, panic when an NMI watchdog timeout occurs (or 'nopanic' to not panic on an NMI watchdog, if CONFIG_BOOTPARAM_HARDLOCKUP_PANIC is set)
# To disable both hard and soft lockup detectors, please see 'nowatchdog'.
# 0 - turn hardlockup detector in nmi_watchdog off
# 1 - turn hardlockup detector in nmi_watchdog on
# Default = 1
# kernel.nmi_watchdog = 0
