# .bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Alias general
alias ls='ls --color=auto'
alias grep='grep --color=auto'

# Prompt
git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
PS1="\[\033[1;32m\]\w\[\033[33m\]\$(git_branch)\[\033[00m\] > "

# Alias Runit
alias svs='sudo sv status /var/service/*'

# Alias XBPS
alias xup='sudo xbps-install -Su'  # Actualizar sistema
alias xin='sudo xbps-install -S'   # Instalar pkg
alias xrmd='sudo xbps-remove -R'   # Desinstalar pkg con dependencias
alias xro='sudo xbps-remove -O'    # Desinstalar pkg obsoletos
alias xrm='sudo xbps-remove'       # Desinstalar pkg
alias xse='xbps-query -Rs'         # Buscar pkg repos
alias xry='xbps-query -s'          # Buscar pkg local
alias Xse='xbps-query -R'          # Buscar pkg dependencias

# Alias Governor
alias powersave='echo powersave | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor'
alias performance='echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor'
